### ISSUE TITLE
[artifactory] Releases deleted sometimes

### ISSUE THREAD

**Issue by captn3m0** [endoflife-date/release-data#124]
See this build: https://github.com/endoflife-date/release-data/actions/runs/5584095126/jobs/10205119374

and this commit: https://github.com/endoflife-date/release-data/commit/476f877b81c61d59843bf5e3861c9e87f2672e2f

Noticed when the next build added them back [here](https://github.com/endoflife-date/release-data/pull/123/commits/dbdc6b2b5154d476cb72226cf013fc8629b6c2d2#diff-14ce848eb9a75cb91ad56cb158a4466364e55bf152a3c054b0893837c0a583a8).

**Comment by dadav** [comment]
The `sleep` value is probably too small: https://github.com/endoflife-date/release-data/blob/main/src/artifactory.py#L27C5-L27C5

**Comment by marcwrobel** [comment]
Yep, that's my best guess too (never experienced this issue locally). I have opened #125 to increase those values.

If it does not fix the issue, we will have to prevent the JSON file to be updated if nothing is retrieved.
