### ISSUE TITLE
Update Data fails for two days

### ISSUE THREAD

**Issue by hebbet** [endoflife-date/release-data#260]
https://github.com/endoflife-date/release-data/actions

Last successful run was two days ago

**Comment by marcwrobel** [comment]
One of the obvious error is the following:

```
 /home/runner/work/release-data/release-data/vendor/bundle/ruby/3.1.0/gems/psych-5.1.1.1/lib/psych/visitors/to_ruby.rb:432:in `visit_Psych_Nodes_Alias': Alias parsing was not enabled. To enable it, pass `aliases: true` to `Psych::load` or `Psych::safe_load`. (Psych::AliasesNotEnabled)
```

Psych is related to YAML parsing, which was required for the git method. Since git is now handled by a Python script, will try to cleanup the script and see if it fixes the script.

**Comment by marcwrobel** [comment]
Thanks for the issue @hebbet. This is fixed.

I did not try to know what happened as the faulty code was not used anymore.
