### ISSUE TITLE
NPM Automation

### ISSUE THREAD

**Issue by captn3m0** [endoflife-date/release-data#33]
Fetch a list of all NPM releases with a script called npm.py and generate a release file: https://github.com/endoflife-date/release-data/tree/main/releases

See

https://github.com/endoflife-date/release-data/issues/15 and https://github.com/endoflife-date/release-data/issues/10 for example.

**Comment by captn3m0** [comment]
To work on this:

1. Clone this repo (`git clone git@github.com:endoflife-date/release-data.git`)
2. Clone the endoflife-date repository inside the website directory (`git clone https://github.com/endoflife-date/endoflife.date website`)
3. Make sure you have Python 3 installed
4. Install dependencies `pip install -r requirements.txt`
5. Run Existing scripts to verify (`python src/pypi.py`) for eg.
6. Update a page belonging to the npm ecosystem in `website/products` to use `auto: npm`
7. Write your npm.py script in the `src` directory and test it against this one project.

**Comment by anartify** [comment]
Have created a pull request for the same: https://github.com/endoflife-date/release-data/pull/36

**Comment by marcwrobel** [comment]
Closed by #36.
