### ISSUE TITLE
azul jdk

### ISSUE THREAD

**Issue by dboehme65** [endoflife-date/release-data#331]
hello 
the Azul JDK have the last Update on Last updated on 25 December 2023
can you trigger  the update periodly? 

I found an new swagger by azul 
https://api.azul.com/metadata/v1/docs/swagger

best regards
D.Böhme

**Comment by marcwrobel** [comment]
Hi @dboehme65, thanks for letting us know.

I think you open your issue to the wrong repository. But it does not matter, I opened https://github.com/endoflife-date/endoflife.date/pull/4808.

Note that [the Azul Zulu page](https://endoflife.date/azul-zulu) is manually updated from Azul release notes, https://docs.azul.com/core/release-notes/release-notes. We already tried to automate it by using the Azul API, but unfortunately it did not work well (more in https://github.com/endoflife-date/endoflife.date/blob/2d9070b833df1513e851d123f45d5b5500513af8/products/azul-zulu.md?plain=1#L21).
