### ISSUE TITLE
GitHub release automation

### ISSUE THREAD

**Issue by marcwrobel** [endoflife-date/release-data#34]
Currently the git tag creation date is used for projects hosted on GitHub. But the tag date does not always match with the release date.

Adding a new `github_release` auto method that fetch releases using the [GitHub releases API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases) and retrieved versions `published_at` date would give more accurate release dates. For example : https://api.github.com/repos/quarkusio/quarkus/releases.

Only the first page should be fetched: there are [rate limit rules](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) in place on the GitHub API.

**Comment by marcwrobel** [comment]
Copied from https://github.com/endoflife-date/endoflife.date/issues/1954.

See #33 for instructions on how to work on this.

**Comment by marcwrobel** [comment]
I have a working draft of the script available on #35.

I made a few test with that PR and I do not think having a `github_release` auto method is a good idea anymore. Github releases are not as accurate as I previously thought:

- in many project creating a GitHub release is a manual process, and it can be easily forgotten (=> wrong date),
- GitHub releases date cannot be set: for older releases the date is either wrong, or the release simply does not exist,
- not all projects hosted on GitHub are using GitHub releases (but all are using tags).

At that occasion I thought about the best way to retrieve releases and releases dates and I think it is, in that order:

1. a package repository (such as Maven Central, NPM, PyPI...) or an API (for products such as GKE): this is the most accurate date because even if the product team did not communicate about it, the release is publicly available.
2. a git tag (if a git repository with appropriate tag is available)
3. a documentation.

Maybe this should be documented somewhere (if not already).

I think I will switch the Quarkus product to `maven` instead of `git` and close this PR and the corresponding issue. Any thought to share before that @captn3m0 ?

**Comment by captn3m0** [comment]
Sounds good. Minor note about precedence, since we support multiple sources: We can track both package repos and git repos for the same product, but that might often be inaccurate as not all git tags graduate to actual releases in all package managers.

**Comment by marcwrobel** [comment]
This issue was closed because Github releases were not as accurate as I previously thought (https://github.com/endoflife-date/release-data/pull/35#issuecomment-1342422387).

With https://github.com/endoflife-date/endoflife.date/pull/2545 it becomes necessary, reopening.
