### ISSUE TITLE
Product info in json files

### ISSUE THREAD

**Issue by artemiux** [endoflife-date/release-data#352]
Thanks for the project. I use it to automatically send notifications every week and I have one suggestion.

Currently, the product name can be extracted from the release file name. For example, **jira.json** corresponds to **jira**. This identifier can be used to generate a [link](https://endoflife.date/jira) to the website. However, this method won't work in some cases. For instance, using **apache-http-server** from **apache-http-server.json** will [return](https://endoflife.date/apache-http-server) a 404 error.

It is suggested to add a **product** object with the appropriate identifier and full name properties inside. For instance, for **releases/apache-http-server.json**, it would be structured as follows:

```json
{
  "product": {
    "name": "apache",
    "fullname": "Apache HTTP Server"
  },
  "releases": {},
  "versions": {
    "2.4.59": {
      "releaseName": "2.4.59",
      "releaseDate": "2024-04-04"
    }
}
```

**Comment by captn3m0** [comment]
The intent is for these to always match, so I've filed a PR to add `apache-http-server` as a redirect: https://github.com/endoflife-date/endoflife.date/pull/5300

This will ensure https://endoflife.date/api/apache-httpd-server.json redirects to https://endoflife.date/api/apache.json, similar to how https://endoflife.date/api/httpd.json redirects right now.

Another alternative is to change the page link to `/apache-http-server`, but unsure about that.

I'll check to see if there are other such pages and file corrections if needed.

---

> It is suggested to add a product object with the appropriate identifier and full name properties inside.

I like the idea of having a `product.identifier` JSON key.

cc @marcwrobel

**Comment by captn3m0** [comment]
Filed https://github.com/endoflife-date/endoflife.date/pull/5301 to fix such issues across all products. Once that is merged, we can add a test to ensure this doesn't break in the future.

**Comment by artemiux** [comment]
Please, add an alternative url for "Palo Alto Networks PAN-OS". Name from _release-data/releases/pan-os.json_ [causes](https://endoflife.date/pan-os) 404.
