### ISSUE TITLE
Support Multiple regexes for `git` type

### ISSUE THREAD

**Issue by captn3m0** [endoflife-date/release-data#41]
For the `distrowatch` type, we support multiple regexes, such as were [used here](https://github.com/endoflife-date/endoflife.date/pull/1505/files).

Supporting a list of regexes, where either one of them matches, will make it easier for us to write and maintain complicated regexes, such as those used in MariaDB. See https://github.com/endoflife-date/endoflife.date/pull/2057/files PR for eg.

**Comment by captn3m0** [comment]
This is how it looked on the code side: https://github.com/endoflife-date/release-data/blob/main/src/distrowatch.py#L18-L20

**Comment by marcwrobel** [comment]
Will be useful for https://endoflife.date/jenkins too.

**Comment by captn3m0** [comment]
Alibaba Dragonwell: https://github.com/endoflife-date/endoflife.date/pull/2773/

**Comment by marcwrobel** [comment]
Should have been closed with #227.
