### ISSUE TITLE
macOS 13.1 missing

### ISSUE THREAD

**Issue by llauren** [endoflife-date/release-data#47]
Hi!

I'm using the macos.json as input for one of my automations and i notice that macOS 13.1 (22C65), released 2022-12-13, is missing from the release data. How can i help? Can i? Should i? Is the data file automatically updated (and is now stuck) or manually curated?

 ~rL

**Comment by llauren** [comment]
I'm getting closer.

Yes, the json release data is automatically populated for macOS. I've now given it a read.
 
And: There is a bug on [Apple's web page](https://support.apple.com/en-us/HT201222): Line 485 says

```
</tr><tr><td><a href="https://support.apple.com/kb/HT213532">macOS Ventura&nbsp;13.1</a></td>
```

Note the `&nbsp;` between Ventura and 13.1.

Solution 1: Get Apple to fix their bug. Hard but correct.

Solution 2: Edit the Regexp in `src/apple.py` to allow for `&nbsp;` in addition to a space character. Stupid but stupid.

What do you think?

**Comment by marcwrobel** [comment]
Hi @llauren,

Nice catch!

The `nbsp;` is not a bug IMHO, because visually it is still as space. And I doubt we will find a way to get Apple to change it ;). So solution 2 may be our only solution.

Are you using the `macos.json` in this repository (https://github.com/endoflife-date/release-data/blob/main/releases/macos.json) or the one on https://endoflife.date (https://endoflife.date/api/macos.json) ? If it is the on in this repository, I suggest you use endoflife.date API instead because it is potentially more up-to-date (it will have both https://github.com/endoflife-date/release-data/blob/main/releases/macos.json and versions added manually in https://github.com/endoflife-date/endoflife.date/blob/master/products/macos.md).

**Comment by llauren** [comment]
I actually submitted a bug report through AppleCare Enterprise 😁 . I'm not sure if Apple will fix the problem, but as for now, it is reported and we're going through route 1.

I have a Python automation which uses the API at https://endoflife.date/api/macos.json and parses it for the versions we want to support ("N" and "N-1", so 13 and 12), then slacks the users with out of date systems. Now the problem of course is that because the data believes macOS 13.0.1 is the latest and greatest, those with this actually out-of-date version won't get a notification.

With the help of pythex.org, i propose the following addition to the file https://github.com/endoflife-date/release-data/blob/main/src/apple.py#L33 :

```
        # Bug compatibility with Apple Support document HT201222 for Ventura 13.1
        r"macOS [\w (&nbsp;)]+(?P<version>\d{2}(?:\.\d+)+)",
```

If you could help me how to create a fix and a pull request?

**Comment by marcwrobel** [comment]
Let me help you on the regex : #48.

**Comment by llauren** [comment]
You are absolutely correct, and i edited my comment above to reflect that. Now, how can a silly little non-coder submit a fix?

**Comment by marcwrobel** [comment]
I already did in #48.

**Comment by llauren** [comment]
Oh, OK. There went my claim to eternal fame 😁 

When will the update be live on the API?

**Comment by marcwrobel** [comment]
The PR must be reviewed by @captn3m0 and after that https://github.com/endoflife-date/endoflife.date must be updated (by some GitHub workflow).

So I would say tomorrow at best.

**Comment by llauren** [comment]
OK, thanks for the cooperation! It's been fun and even a tad enlightening!

**Comment by llauren** [comment]
OK, thanks for the cooperation! It's been fun and even a tad enlightening!

**Comment by captn3m0** [comment]
Give me a few hours. I remember explicitly fixing the .0 versions somehow, want to double check that before merging.

**Comment by marcwrobel** [comment]
@llauren, macOS 13.1 is now on https://endoflife.date/macos. Thanks again for your contribution.
