### ISSUE TITLE
Date retrieved for Tails 1.0 does not match source tag date

### ISSUE THREAD

**Issue by marcwrobel** [endoflife-date/release-data#58]
The date on https://gitlab.tails.boum.org/tails/tails/-/tags/1.0 and the date retrieved for 1.0 in https://github.com/endoflife-date/release-data/blob/main/releases/tail.json don't match.

**Comment by captn3m0** [comment]
The annotated tag itself was created in 2015 (Running `git show 1.0` on the repo), while the commit backing that tag was created in 2014:

```
tag 1.0
Tagger: Tails developers <tails@boum.org>
Date:   Wed Feb 25 12:35:37 2015 +0000

tagging version 1.0
-----BEGIN PGP SIGNATURE-----

iQIcBAABCgAGBQJU7cGZAAoJEBICghy+LNnBaxUP+wSLUcA5284niiiZIsC4jIq4
2aaD6xJiKDNIYYkP+CvwN7Z1uEvBE8H9bts/O6sbDvz3YrjMyIVZOgRpvC437oIv
zL+Gp1Ge3nV2hh+o2vYZBf7wwlEGNYiAkVNF2/CYgJ/BiFF+DGIHzzKPEYNPo7L4
Q2GEAwDgFB7M8b0M59nsEXlWS5Qj1AFvooG24GIzdPyEkurzX93Ox1Rk1bUqUJBn
wIj7uA8UTcjBN+4LtEem7LUJqJu6eGVCMtAeKT2HsMEaCJhrl5ZsZ0U4i6FvUrcF
bQAK2uPIoo0AQ+qC/WH+arHrddOrze4uhKyis4mHS/FxE3f2LWy7ucnegg6t82tk
9IuFO5g47629mY/kiGNYTqtCJxUCoGbWaI4Afdokb8ZawJv9bMHuwp8zB529kX0F
YKJl3/uyOs07+J56+/sZWw9sG4wS3F3dI/JYnnSzVRR0jsc7ot5wXCAFkER9gMJm
11og6xiOQSK114hcZNY4DLmvn7YJ5EXiK7Z5VXIWklXSvzBQzRtcfkxzH8ba34rX
U4zGLw/N2hHM9vWgOxgYfg8mOlVeMQEfgWIYv0Z3nr5WhuZyYcVLnQEHVW3PqC4o
7R1/yBxOUguGbjqlwty/mByUhxFz5ciofVhx2Rt3GYbGY3xhQSwo41XtwHQyJW/C
nclzMfk314KSZZwUHKLH
=8/m4
-----END PGP SIGNATURE-----

commit 5efd241566a557272f7b66d36c19e79775279c4d
Author: Tails developers <amnesia@boum.org>
Date:   Sun Apr 27 20:57:16 2014 +0200

    Fix broken translation.

diff --git a/po/tr.po b/po/tr.po
index 73145caa1f..3c190f2fa3 100644
--- a/po/tr.po
+++ b/po/tr.po
@@ -240,7 +240,7 @@ msgstr "Tor Browser'ı başlat"
 
 #: config/chroot_local-includes/usr/local/bin/iceweasel:15
 msgid "Cancel"
-msgstr "İptal\n"
+msgstr "İptal"
 
 #: config/chroot_local-includes/usr/local/bin/shutdown_helper_applet:34
 msgid "Shutdown Immediately"
```

GitLab is picking the commit date, instead of the tag date, which is definitely wrong. This seems to be a missing feature in GitLab: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/3690

Probably all the annotated tags till 1.3 were created much later after the commits: https://github.com/endoflife-date/release-data/blob/main/releases/tail.json#L2-L11

We could maybe switch to https://distrowatch.com/index.php?distribution=tails, which seems to have more releases.

**Comment by captn3m0** [comment]
Created a mirror on GitHub, and it shows the correct tagging date: https://github.com/captn3m0/tails-temp-mirror/releases/tag/1.0

**Comment by marcwrobel** [comment]
@captn3m0, do not forget to commit https://github.com/endoflife-date/endoflife.date/commit/93d7e10e7fcb46b442672348bcd98087cddd4c7e.

**Comment by captn3m0** [comment]
Thanks for the reminder 🥇

**Comment by marcwrobel** [comment]
@captn3m0, can we close this issue ?

**Comment by captn3m0** [comment]
Data looks good: https://github.com/endoflife-date/release-data/commit/d570b4a624bc1eac5ed774cd632acd233ed5d393

Closing.
