### ISSUE TITLE
Automatically delete branches when pull request are successfully merged and closed

### ISSUE THREAD

**Issue by marcwrobel** [endoflife-date/release-data#62]
Currently, when a pull request is merged, the associated branche must be deleted manually. We should set up the repository to delete branches when pull request are successfully merged and closed.

This setting, named _Automatically delete head branches_, can be found on https://github.com/endoflife-date/release-data/settings.

**Comment by captn3m0** [comment]
Updated. Enabled auto-merge as well.

![image](https://user-images.githubusercontent.com/584253/210422598-8e74b8d9-dfd8-4fab-9b42-ffb1b8e0b757.png)
