### ISSUE TITLE
Block merging of PRs until the Update data task as completed successfuly

### ISSUE THREAD

**Issue by marcwrobel** [endoflife-date/release-data#68]
Currently it is possible to merge a PR even if the GitHub action _Update Data_ task is not completed. `main` branch protection rules should be configured to make it impossible using the _Require status checks to pass before merging _ option in the project settings.

**Comment by captn3m0** [comment]
![image](https://user-images.githubusercontent.com/584253/211851942-ce62bd04-cce3-4eee-a28c-3b289155250c.png)

**Comment by captn3m0** [comment]
This breaks our automation, since that also runs on the `main` branch:


```remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Required status check "Update data" is expected.        
```

https://github.com/endoflife-date/release-data/actions/runs/3898391289/jobs/6657081358

Reverting for now, and re-opening this.

**Comment by marcwrobel** [comment]
Closing this as as I don't see any simple way to have both a working automation and PR blocked for now.
