### ISSUE TITLE
Add Plesk automation 

### ISSUE THREAD

**Issue by marcwrobel** [endoflife-date/release-data#78]
Automate Plesk versions retrieval by parsing https://docs.plesk.com/release-notes/obsidian/change-log/.

See https://github.com/endoflife-date/endoflife.date/pull/2544?notification_referrer_id=NT_kwDOAC2bcLI1NjUzNzg0NjU0OjI5ODg5MTI#discussion_r1112272072.

**Comment by marcwrobel** [comment]
Done (https://github.com/endoflife-date/release-data/commit/cd3af955000b677502b238190b97dfa353837045), closing.

Thanks again @sibprogrammer .

**Comment by sibprogrammer** [comment]
@marcwrobel thank you for your awesome project! :)

**Comment by marcwrobel** [comment]
You're welcome, @endoflife-date/everyone you have the thanks of @sibprogrammer ;).
