### ISSUE TITLE
PHP: Custom Automation

### ISSUE THREAD

**Issue by captn3m0** [endoflife-date/release-data#90]
Ref: https://github.com/endoflife-date/endoflife.date/issues/2822

PHP tags their releases a few days before the announcement, so there's a short duration where our `latest` information is incorrect.

Use the https://www.php.net/releases/index.php?json&max=100&version=4 API instead of the git tags.

**Comment by marcwrobel** [comment]
Closed by #91. Dates updated by https://github.com/endoflife-date/release-data/commit/f34f4863fca4ded1e39b2033bb5e0dec268f2637.
